INSERT INTO categorie (nom_categorie)
VALUES ('Global'),
       ('Domestique'),
       ('Maison'),
       ('Animal domestique'),
       ('Animal sauvage'),
       ('Insecte et reptile'),
       ('Fruit'),
       ('Jour de la semaine'),
       ('Jours dans le mois'),
       ('Mois'),
       ('Planètes'),
       ('Couleurs'),
       ('Famille'),
       ('Vêtement'),
       ('Corps'),
       ('Transport'),
       ('Bâtiment'),
       ('Repère spatial'),
       ('Repère temporel'),
       ('Nourriture'),
       ('Halloween'),
       ('Noël'),
       ('Saint Valentin'),
       ('Été'),
       ('Pays'),
       ('Japon'),
       ('Nombre'),
       ('Unité de mesure'),
       ('Formule de politesse');

INSERT INTO mot(mot_kanji, mot_hiragana, mot_katakana, traduction, type, terminaison, groupe)
VALUES ('人', 'ひと', 'ニン', 'La personne', 'nom_commun', null, null),
       ('女', 'おんあ', null, 'La femme, le féminin', 'nom_commun', null, null),
       ('男', 'おとこ', null, 'L''homme, le masculin', 'nom_commun', null, null),
       ('子', 'こ', null, 'L''enfant', 'nom_commun', null, null),
       ('火', 'ひ', 'カ', 'Le feu', 'nom_commun', null, null),
       ('水', 'みず', 'スイ', 'L''eau', 'nom_commun', null, null),
       ('土', 'つち', 'ド', 'La terre', 'nom_commun', null, null),
       ('山', 'やま', 'サン', 'La montagne', 'nom_commun', null, null),
       ('川', 'かわ', null, 'La rivière', 'nom_commun', null, null),
       ('雨', 'あめ', null, 'La pluie', 'nom_commun', null, null),
       ('雪', 'ゆき', null, 'La neige', 'nom_commun', null, null),
       ('風', 'かぜ', 'フ', 'Le vent', 'nom_commun', null, null),
       ('日', 'ひ', 'ニチ', 'Le soleil, le jour', 'nom_commun', null, null),
       ('月', 'つき', 'ゲツ', 'La lune, le mois', 'nom_commun', null, null),
       ('花', 'はな', null, 'La fleur', 'nom_commun', null, null),
       ('お金', 'おかね', null, 'L''argent', 'nom_commun', null, null),
       ('金', 'かね', 'キン', 'L''or', 'nom_commun', null, null),
       ('京', 'みやこ', 'キョウ', 'La capitale', 'nom_commun', null, null),
       ('国', 'くに', 'コク', 'Le pays', 'nom_commun', null, null),
       ('本', 'もと', 'ホン', 'L''origine,la base, le livre', 'nom_commun', null, null),
       ('名', 'な', 'メイ', 'Le nom', 'nom_commun', null, null),
       ('卵', 'たまご', 'ラン', 'L''oeuf', 'nom_commun', null, null),
       ('血', 'ち', 'ケツ', 'Le sang', 'nom_commun', null, null),
       ('波', 'なみ', 'ハ', 'La vague', 'nom_commun', null, null),
       ('心', 'こころ', 'ツン', 'Le coeur', 'nom_commun', null, null),
       ('私', 'わたし', null, 'Moi', 'nom_commun', null, null),
       ('円', 'えん', null, 'Le yen', 'nom_commun', null, null),
       ('田', 'た', null, 'La rizière', 'nom_commun', null, null),
       ('島', 'しま', null, 'L''île', 'nom_commun', null, null),

       ('分かる', 'わかる', null, 'Comprendre', 'verbe', 'る', 1),
       ('飲む', 'のむ', null, 'Boire', 'verbe', 'む', 1),
       ('読む', 'よむ', null, 'Lire', 'verbe', 'む', 1),
       ('話す', 'はなす', null, 'Parler', 'verbe', 'す', 1),
       ('思う', 'おもう', null, 'Penser', 'verbe', 'う', 1),
       ('言う', 'いう', null, 'Dire', 'verbe', 'う', 1),
       ('聞く', 'かく', null, 'Écouter', 'verbe', 'く', 1),
       ('歩く', 'はるく', null, 'Marcher', 'verbe', 'く', 1),
       ('知る', 'しる', null, 'Savoir', 'verbe', 'る', 1),
       ('書く', 'きく', null, 'Écrire', 'verbe', 'く', 1),
       ('帰る', 'かえる', null, 'Rentrer (chez soi)', 'verbe', 'る', 1),
       ('戻る', 'もどる', null, 'Revenir, retourner', 'verbe', 'る', 1),
       ('向かう', 'むかう', null, 'avancer, progresser, se diriger vers', 'verbe', 'う', 1),
       ('買う', 'かう', null, 'Acheter', 'verbe', 'う', 1),
       ('遊ぶ', 'あそぶ', null, 'Jouer', 'verbe', 'ぶ', 1),
       ('泳ぐ', 'およぐ', null, 'Nager', 'verbe', 'ぐ', 1),
       ('泣く', 'なく', null, 'Pleurer', 'verbe', 'く', 1),
       ('笑う', 'わらう', null, 'Rire', 'verbe', 'う', 1),
       ('進む', 'すすむ', null, 'Passer, avancer', 'verbe', 'む', 1),
       ('飛ぶ', 'とぶ', null, 'Voler (dans les airs)', 'verbe', 'ぶ', 1),
       ('切る', 'きる', null, 'Couper', 'verbe', 'る', 1),
       ('吸う', 'すう', null, 'Fumer', 'verbe', 'う', 1),
       ('治す', 'なおす', null, 'Soigner', 'verbe', 'す', 1),
       ('送る', 'おくる', null, 'Envoyer', 'verbe', 'る', 1),
       ('始まる', 'はじまる', null, 'Commencer', 'verbe', 'る', 1),
       ('終わる', 'おわる', null, 'Se terminer', 'verbe', 'る', 1),
       ('戦う', 'たたかう', null, 'Se battre', 'verbe', 'う', 1),
       ('守る', 'まもる', null, 'Protéger', 'verbe', 'る', 1),
       ('吐く', 'はく', null, 'Cracher, vomir', 'verbe', 'く', 1),
       ('着く', 'つく', null, 'Arriver', 'verbe', 'く', 1),
       ('残る', 'のこる', null, 'Rester', 'verbe', 'る', 1),
       ('脱ぐ', 'ぬぐ', null, 'Se déshabiller', 'verbe', 'ぐ', 1),
       ('急ぐ', 'いそぐ', null, 'Se dépêcher', 'verbe', 'ぐ', 1),
       ('探す', 'さがす', null, 'Chercher', 'verbe', 'す', 1),
       ('殺す', 'ころす', null, 'Tuer', 'verbe', 'す', 1),
       ('待つ', 'まつ', null, 'Attendre', 'verbe', 'つ', 1),
       ('立つ', 'たつ', null, 'Être debout', 'verbe', 'つ', 1),
       ('勝つ', 'かつ', null, 'Gagner', 'verbe', 'つ', 1),
       ('死ぬ', 'しぬ', null, 'Mourir', 'verbe', 'ぬ', 1),
       ('選ぶ', 'えらぶ', null, 'Choisir', 'verbe', 'ぶ', 1),
       ('休む', 'やすむ', null, 'Se reposer', 'verbe', 'む', 1),
       ('売る', 'うる', null, 'Vendre', 'verbe', 'る', 1),
       ('乗る', 'のる', null, 'Monter à bord', 'verbe', 'る', 1),
       ('会う', 'あう', null, 'Rencontrer', 'verbe', 'う', 1),
       ('住む', 'すむ', null, 'Habiter', 'verbe', 'む', 1),
       ('走る', 'はしる', null, 'Courir', 'verbe', 'る', 1),
       ('注ぐ', 'そそぐ', null, 'Verser', 'verbe', 'ぐ', 1),
       ('変わる', 'かわる', null, 'Se changer en', 'verbe', 'る', 1),
       ('呼ぶ', 'よぶ', null, 'Appeler', 'verbe', 'ぶ', 1),
       ('入る', 'はいる', null, 'Entrer', 'verbe', 'る', 1),
       ('持つ', 'もつ', null, 'Tenir', 'verbe', 'つ', 1),
       ('', 'やる', null, 'Faire (pour le sport, exprimer la motivation)', 'verbe', 'る', 1),
       ('要る', 'いる', null, 'Être nécessaire', 'verbe', 'る', 1),
       ('蹴る', 'ける', null, 'Frapper du pied', 'verbe', 'る', 1),
       ('使う', 'つかう', null, 'Utiliser quelque chose, faire usage de', 'verbe', 'う', 1),
       ('', 'いる', null, 'Être ou avoir, pour les êtres vivants', 'verbe', 'る', 2),
       ('見る', 'みる', null, 'Écrire', 'verbe', 'る', 2),
       ('食べる', 'たべる', null, 'Manger', 'verbe', 'る', 2);