INSERT INTO categorie (nom_categorie)
VALUES ('Global'),
       ('Domestique'),
       ('Maison'),
       ('Animal domestique'),
       ('Animal sauvage'),
       ('Insecte et reptile'),
       ('Fruit'),
       ('Jour de la semaine'),
       ('Jours dans le mois'),
       ('Mois'),
       ('Planètes'),
       ('Couleurs'),
       ('Famille'),
       ('Vêtement'),
       ('Corps'),
       ('Transport'),
       ('Bâtiment'),
       ('Repère spatial'),
       ('Repère temporel'),
       ('Nourriture'),
       ('Halloween'),
       ('Noël'),
       ('Saint Valentin'),
       ('Été'),
       ('Pays'),
       ('Japon'),
       ('Nombre'),
       ('Unité de mesure'),
       ('Formule de politesse');

INSERT INTO mot(mot_kanji, mot_hiragana, mot_katakana, traduction, type, terminaison, groupe)
VALUES ('人', 'ひと', 'ニン', 'La personne', 'nom_commun', null, null),
       ('女', 'おんあ', null, 'La femme, le féminin', 'nom_commun', null, null),
       ('男', 'おとこ', null, 'L''homme, le masculin', 'nom_commun', null, null),
       ('子', 'こ', null, 'L''enfant', 'nom_commun', null, null),
       ('火', 'ひ', 'カ', 'Le feu', 'nom_commun', null, null),
       ('水', 'みず', 'スイ', 'L''eau', 'nom_commun', null, null),
       ('土', 'つち', 'ド', 'La terre', 'nom_commun', null, null),
       ('山', 'やま', 'サン', 'La montagne', 'nom_commun', null, null),
       ('川', 'かわ', null, 'La rivière', 'nom_commun', null, null),
       ('雨', 'あめ', null, 'La pluie', 'nom_commun', null, null),
       ('雪', 'ゆき', null, 'La neige', 'nom_commun', null, null),
       ('風', 'かぜ', 'フ', 'Le vent', 'nom_commun', null, null),
       ('日', 'ひ', 'ニチ', 'Le soleil, le jour', 'nom_commun', null, null),
       ('月', 'つき', 'ゲツ', 'La lune, le mois', 'nom_commun', null, null),
       ('花', 'はな', null, 'La fleur', 'nom_commun', null, null),
       ('お金', 'おかね', null, 'L''argent', 'nom_commun', null, null),
       ('金', 'かね', 'キン', 'L''or', 'nom_commun', null, null),
       ('京', 'みやこ', 'キョウ', 'La capitale', 'nom_commun', null, null),
       ('国', 'くに', 'コク', 'Le pays', 'nom_commun', null, null),
       ('本', 'もと', 'ホン', 'L''origine,la base, le livre', 'nom_commun', null, null),
       ('名', 'な', 'メイ', 'Le nom', 'nom_commun', null, null),
       ('卵', 'たまご', 'ラン', 'L''oeuf', 'nom_commun', null, null),
       ('血', 'ち', 'ケツ', 'Le sang', 'nom_commun', null, null),
       ('波', 'なみ', 'ハ', 'La vague', 'nom_commun', null, null),
       ('心', 'こころ', 'ツン', 'Le coeur', 'nom_commun', null, null),
       ('私', 'わたし', null, 'Moi', 'nom_commun', null, null),
       ('円', 'えん', null, 'Le yen', 'nom_commun', null, null),
       ('田', 'た', null, 'La rizière', 'nom_commun', null, null),
       ('島', 'しま', null, 'L''île', 'nom_commun', null, null);